language: objective-c
osx_image: xcode10

script:
- xcodebuild -workspace Stylize.xcworkspace -scheme Stylize -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' build test
